### PR TITLE
Add option to select current working directory (cwd).

### PR DESCRIPTION
**Pull request by shishir-a412ed**

### CODE REVIEW

**Comment by Vulfox** [comment]
Do any docs need to be updated for this new parameter?

**Comment by shishir-a412ed** [comment]
> Do any docs need to be updated for this new parameter?

@Vulfox It's `work in progress`, that's why I added a `do-not-review` label :)

**Comment by Vulfox** [comment]
My apologies, saw the review request and didn't see the label haha

**Comment by shishir-a412ed** [comment]
@Vulfox Please review.

**Review by Vulfox — APPROVED** [review]
LGTM

**Pull request merged**
