### PR TITLE
Update dependabot dependencies

### PR DESCRIPTION
**Pull request by shishir-a412ed**
```
HQ-JC067RWDF2:nomad-driver-containerd smahajan$ make build
/usr/local/go/bin/go build -o containerd-driver .
HQ-JC067RWDF2:nomad-driver-containerd smahajan$ echo $?
0
```

### CODE REVIEW

**Comment by slonopotamus** [comment]
I believe an even better job was already done in https://github.com/Roblox/nomad-driver-containerd/pull/176

**Comment by shishir-a412ed** [comment]
@slonopotamus I missed that! We can close this one and merge #176 
Shall we close #170 since it's already included in #176 ?

**Comment by slonopotamus** [comment]
> Shall we close https://github.com/Roblox/nomad-driver-containerd/pull/170 since it's already included in https://github.com/Roblox/nomad-driver-containerd/pull/176 ?

If #176 is merged, sure.

**Comment by shishir-a412ed** [comment]
Closing this in favor of #176

**Pull request closed without merging**
