### PR TITLE
Docker registry auth support via driver config.

### PR DESCRIPTION
**Pull request by shishir-a412ed**
This PR addresses Option-1 in [`this`](https://github.com/Roblox/nomad-driver-containerd/issues/92#issuecomment-863532072)

Signed-off-by: Shishir Mahajan <smahajan@roblox.com>

### CODE REVIEW

**Comment by shishir-a412ed** [comment]
Added @austinmacrbx for review.

**Comment by austinmacrbx** [comment]
I'm getting the following error when running `sudo ./run_tests.sh 010-test-allow-privileged.sh` in my vagrant VM. Is this intended? 

```
WARNING: Local host detected.
WARNING: These tests are designed to be run as part of continous integration (CI) and not recommended to be run on local host.
WARNING: These tests are destructive and can modify (or destroy) software on your host system.
WARNING: If running the tests locally, run it in the vagrant VM provided with the repository.
Do you still want to run the tests (Y/N)? y
INFO: Running tests on local host (vagrant VM). Setup is not required.
INFO: Checking if nomad-driver-containerd is up and running, and nomad is ready to accept jobs.
INFO: containerd driver is up and running.
INFO: Running test 010-test-allow-privileged.sh
~/go/src/github.com/Roblox/nomad-driver-containerd/example ~/go/src/github.com/Roblox/nomad-driver-containerd/tests
INFO: nomad.service is up and running
INFO: Starting nomad privileged-not-allowed job using nomad-driver-containerd.
Error submitting job: Put "http://127.0.0.1:4646/v1/jobs": dial tcp 127.0.0.1:4646: connect: connection refused
INFO: Checking status of privileged-not-allowed job.
No job(s) with prefix or id "privileged-not-allowed" found
This command takes one of the following argument conditions:
 * A single <allocation>
 * No arguments, with output format specified
For additional help try 'nomad alloc status -help'
ERROR: privileged-not-allowed should have failed to run.
INFO: nomad.service is up and running
```

**Comment by shishir-a412ed** [comment]
@austinmacrbx 
I tried it on my vagrant VM and it works for me.

```
vagrant@vagrant:~/go/src/github.com/Roblox/nomad-driver-containerd/tests$ sudo ./run_tests.sh 010-test-allow-privileged.sh
WARNING: Local host detected.
WARNING: These tests are designed to be run as part of continous integration (CI) and not recommended to be run on local host.
WARNING: These tests are destructive and can modify (or destroy) software on your host system.
WARNING: If running the tests locally, run it in the vagrant VM provided with the repository.
Do you still want to run the tests (Y/N)? y
INFO: Running tests on local host (vagrant VM). Setup is not required.
INFO: Checking if nomad-driver-containerd is up and running, and nomad is ready to accept jobs.
INFO: containerd driver is up and running.
INFO: Running test 010-test-allow-privileged.sh
~/go/src/github.com/Roblox/nomad-driver-containerd/example ~/go/src/github.com/Roblox/nomad-driver-containerd/tests
INFO: nomad.service is up and running
INFO: Starting nomad privileged-not-allowed job using nomad-driver-containerd.
==> Monitoring evaluation "2c1b9543"
    Evaluation triggered by job "privileged-not-allowed"
    Evaluation within deployment: "2eee732c"
    Allocation "96372fb1" created: node "eb9fc499", group "privileged-not-allowed-group"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "2c1b9543" finished with status "complete"
INFO: Checking status of privileged-not-allowed job.
INFO: purge nomad privileged-not-allowed job.
==> Monitoring evaluation "b90074d3"
    Evaluation triggered by job "privileged-not-allowed"
    Evaluation within deployment: "2eee732c"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "b90074d3" finished with status "complete"
~/go/src/github.com/Roblox/nomad-driver-containerd/tests
INFO: nomad.service is up and running
PASS: 010-test-allow-privileged.sh
```

I have seen some race conditions in the past, where `systemd` reports the service as up and running, however when you try to launch the nomad job, `nomad` is not really ready. I believe this is one of those cases.

- The test calls [`is_systemd_service_active`](https://github.com/Roblox/nomad-driver-containerd/blob/master/tests/010-test-allow-privileged.sh#L14) which makes sure that systemd `nomad.service` is up and running. The method `is_systemd_service_active` is defined [`here`](https://github.com/Roblox/nomad-driver-containerd/blob/master/tests/utils.sh#L48)
- The test then tries to launch the job, and fails (with the below error message) since nomad is still *not* ready to receive requests.

```
Error submitting job: Put "http://127.0.0.1:4646/v1/jobs": dial tcp 127.0.0.1:4646: connect: connection refused
```

Any specific reason you are trying to run just `010-test-allow-privileged.sh` and not the whole test suite?

**Comment by austinmacrbx** [comment]
I ran the whole test suite initially, but I came across the error in test 10, so I just ran it separately. 

Also, `priviliged-not-allowed` should fail right? It is running on my machine.

```
vagrant@vagrant:~/go/src/github.com/Roblox/nomad-driver-containerd/example$ nomad job status privileged-not-allowed
ID            = privileged-not-allowed
Name          = privileged-not-allowed
Submit Date   = 2021-06-28T20:40:46Z
Type          = service
Priority      = 50
Datacenters   = dc1
Namespace     = default
Status        = running
Periodic      = false
Parameterized = false

Summary
Task Group                    Queued  Starting  Running  Failed  Complete  Lost
privileged-not-allowed-group  0       0         1        0       0         0

Latest Deployment
ID          = f61a96ed
Status      = successful
Description = Deployment completed successfully

Deployed
Task Group                    Desired  Placed  Healthy  Unhealthy  Progress Deadline
privileged-not-allowed-group  1        1       1        0          2021-06-28T20:51:02Z

Allocations
ID        Node ID   Task Group                    Version  Desired  Status   Created   Modified
fd72eddc  6e64ae5e  privileged-not-allowed-group  0        run      running  5m5s ago  4m50s ago
```

**Comment by austinmacrbx** [comment]
LGTM

**Review by austinmacrbx — APPROVED** [review]

**Pull request merged**
