### PR TITLE
Upgrade build dependencies

### PR DESCRIPTION
**Pull request by shoenig**
This PR upgrades dependencies

By updating the go.mod build mode from 1.12 to 1.17 and upgrading
directly imported dependencies, we can eliminate all of the `replace`
directives that were needed previously (they've since been resolved).

The split require blocks are a new feature of the go tooling.

### CODE REVIEW

**Comment by shishir-a412ed** [comment]
Adding a comment to make CLA bot happy!

**Comment by shishir-a412ed** [comment]
@shoenig Can you sign the CLA?

**Comment by shoenig** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by shishir-a412ed — APPROVED** [review]
LGTM!

**Pull request merged**
