### PR TITLE
Change filesystem isolation to FSIsolationImage.

### LINKED ISSUE #58: [question] Is it production ready?
Hello,

I know this question usually have an answer like "it depends" but I wonder what is the current state of this module from your point of view?

Also, I see in Nomad docs what:

> filesystem isolation	none

Does it mean that allocations run with it have full access to underlying fs?

### PR DESCRIPTION
**Pull request by shishir-a412ed**
Fixes #58

### CODE REVIEW

**Review by shivdudhani — DISMISSED** [review]
LGTM

**Review by Vulfox — APPROVED** [review]
LGTM. Version bump?

**Comment by shishir-a412ed** [comment]
@Vulfox 
> LGTM. Version bump?

At some point, I will automate the release process using `github actions`. For now, I am not releasing (bumping version) every time I merge to `master`. I release it (and bump up the version) once I have merged sufficient changes, that warrant a new release. I agree 🙂 the system is not perfect right now, and probably could be improved.

**Comment by shishir-a412ed** [comment]
The CI seems to be failing for a legit reason. Holding on to the merge while I dig deeper.

**Comment by shishir-a412ed** [comment]
@shivdudhani @Vulfox Can you take another look? I have fixed the CI issue. More details [`here`](https://github.com/hashicorp/nomad/issues/9790)

@tgross Can you also take a quick glance and see if I didn't miss anything? TIA

**Review by Vulfox — APPROVED** [review]
LGTM after reading https://github.com/hashicorp/nomad/issues/9790, things seem aligned.

**Pull request merged**
